### ISSUE TITLE
Verify Thread-safty in RestTemplateBuilder

### ISSUE THREAD

**Issue by meip** [swisscom/open-service-broker#109]
# Problem
OSB got stuck for all k8s provisioning within this stack trace:

```INFO 11568 --- [stence_Worker-5] c.s.c.s.b.p.j.ServiceDeprovisioningJob   : About to request service deprovisioning, LastOperation{id=31588, guid='cb8ceec5-7e7e-429c-96fe-0f0140cb8b13', operation=deprovision, dateCreation=42:45.0, status=in_progress, description='null', internalState='null'}
INFO 11568 --- [stence_Worker-5] c.s.c.s.b.s.c.ServiceProviderLookup      : Lookup for bean:kubernetesRedisServiceProvider
WARN 11568 --- [stence_Worker-5] c.s.c.s.b.a.j.AbstractLastOperationJob   : Job execution with id:cb8ceec5-7e7e-429c-96fe-0f0140cb8b13 failed

java.util.NoSuchElementException: null
        at java.util.ArrayList$Itr.next(ArrayList.java:854) ~[na:1.8.0_131]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.removeAll(DefaultGroovyMethods.java:4416) ~[groovy-all-2.4.7.jar!/:2.4.7]
        at com.swisscom.cloud.sb.broker.util.RestTemplateBuilder.addLoggingRequestInterceptor(RestTemplateBuilder.groovy:73) ~[broker-2.12.1.jar!/:na]
        at com.swisscom.cloud.sb.broker.util.RestTemplateBuilder.build(RestTemplateBuilder.groovy:63) ~[broker-2.12.1.jar!/:na]
        at com.swisscom.cloud.sb.broker.services.kubernetes.client.rest.KubernetesClient.exchange(KubernetesClient.groovy:31) ~[broker-2.12.1.jar!/:na]
        at com.swisscom.cloud.sb.broker.services.kubernetes.client.rest.KubernetesClient$exchange.call(Unknown Source) ~[na:na]
        at com.swisscom.cloud.sb.broker.services.kubernetes.facade.AbstractKubernetesFacade.deprovision(AbstractKubernetesFacade.groovy:85) ~[broker-2.12.1.jar!/:na]
        at com.swisscom.cloud.sb.broker.services.kubernetes.service.state.KubernetesServiceDeprovisionState$1.triggerAction(KubernetesServiceDeprovisionState.groovy:20) ~[broker-2.12.1.jar!/:na]```

**Comment by meip** [comment]
Done in #105
