### ISSUE TITLE
Missing artifacts on maven central

### ISSUE THREAD

**Issue by bytestack** [swisscom/open-service-broker#266]
# Problem
The last two release train versions (6.6.18 and 6.6.17) are incomplete on maven central. According to the build pipeline there was a `SocketException `but the pipeline didn't fail.

![image](https://user-images.githubusercontent.com/8089561/58306564-2ce5d080-7dfc-11e9-97ba-536e1f78f4db.png)

Truncated log output:
```
> Task :client:syncVersionToMavenCentral
Trying to publish a new version to Bintray failed.
java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
```

# Proposal
- Fix the build pipeline so that it fails when build artifacts could not be published to the maven central repository.

# Links
- [Build pipeline output](https://circleci.com/gh/swisscom/open-service-broker/1058)

**Comment by ampersand8** [comment]
Yeah, it's strange that it was not marked as failed. Seems like the exit code `0` was given. IMHO this is a bug either in gradle or the nebula-publishing-plugin, as we only execute `./gradlew publish` and expect to get exit code non-zero if anything fails.
